// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PRACTICA_H
#define PRACTICA_H

#include <ngrest/common/Service.h>
#include <listacircular.h>
#include <cola.h>
#include <list>

struct usuarioN
{
    std::string id;
    std::string nombre;
    std::string correo;
    std::string fecha;
};

struct recursoN
{
    std::string dominio;
    std::string contenido;
    
};

typedef usuarioN datos_usuario_serial;
typedef recursoN datos_recurso_serial;

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: practica
class Practica: public ngrest::Service
{
public:
    // Here is an example of service operation
    //! Dummy description for the operation
    /*! Some detailed description of the operation */
    // To invoke this operation from browser open: http://localhost:9098/practica/World!
    //
    // '*location' metacomment sets path to operation relative to service operation.
    // Default value is operation name.
    // This will bind "echo" method to resource path: http://host:port/practica/{text}
    // *location: /{text}
    //
    // '*method' metacomment sets HTTP method for the operation. GET is default method.
    // *method: GET
    //
    std::string echo(const std::string& text);

    // *location: /newuser/{user}
    //! Insertar Usuario
    /*! Permite ingresar un usuario  */
    // *method: POST
    

    std::string newuser(datos_usuario_serial user);
    
     // *location: /getusuarios
    //! Obtener Usuario
    /*! Despliega lo usuarios  */
    // *method: GET

    std::list<datos_usuario_serial> getuser();

    // *location: /newrecurso
    //! Insertar Recurso
    /*! Permite ingresar un usuario  */
    // *method: POST
    

    std::string newrecurso(datos_recurso_serial recu);
    

    // *location: /getrecurso
    //! Obtener recurso
    /*! Despliega los recursos  */
    // *method: GET

    std::list<datos_recurso_serial> getrecurso();
};


#endif // PRACTICA_H



